// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.WEB.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            LivroCliente = new HashSet<LivroCliente>();
        }

        public int Id { get; set; }
        public string Cpf { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Numero { get; set; }
        public string TelefoneCelular { get; set; }
        public string TelefoneFixo { get; set; }

        public virtual ICollection<LivroCliente> LivroCliente { get; set; }
    }
}