// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Livraria.WEB.Models
{
    public partial class Livro
    {
        public Livro()
        {
            LivroCliente = new HashSet<LivroCliente>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public string Autor { get; set; }
        public string Editora { get; set; }
        public DateTime AnoPublicacao { get; set; }
        public string Edicao { get; set; }

        public virtual ICollection<LivroCliente> LivroCliente { get; set; }
    }
}