// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Livraria.DATA.Models
{
    [Table("Livro_Cliente")]
    public partial class LivroCliente
    {
        [Key]
        public int Id { get; set; }
        public int? IdCliente { get; set; }
        public int? IdLivro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataEntrega { get; set; }
        public bool? Entregue { get; set; }

        [ForeignKey(nameof(IdCliente))]
        [InverseProperty(nameof(Cliente.LivroCliente))]
        public virtual Cliente IdClienteNavigation { get; set; }
        [ForeignKey(nameof(IdLivro))]
        [InverseProperty(nameof(Livro.LivroCliente))]
        public virtual Livro IdLivroNavigation { get; set; }
    }
}