// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Livraria.DATA.Models
{
    public partial class Livro
    {
        public Livro()
        {
            LivrosCliente = new HashSet<LivrosClientes>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [StringLength(100)]
        public string Autor { get; set; }
        [Required]
        [StringLength(100)]
        public string Editora { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AnoPublicacao { get; set; }
        [Required]
        [StringLength(50)]
        public string Edicao { get; set; }

        [InverseProperty("IdLivroNavigation")]
        public virtual ICollection<LivrosClientes> LivrosCliente { get; set; }
    }
}