// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Livraria.DATA.Models
{
    [Keyless]
    public partial class VwEmprestimo
    {
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        public string Cpf { get; set; }
        [Required]
        [StringLength(100)]
        public string NomeCliente { get; set; }
        [Required]
        [StringLength(50)]
        public string NomeLivro { get; set; }
        public int Id { get; set; }
        public int? IdCliente { get; set; }
        public int? IdLivro { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataEmprestimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DataEntrega { get; set; }
        public bool? Entregue { get; set; }
    }
}